import type { Metadata } from "next";
import { Wrapper } from "@/components/sections";
import "@/styles/index.scss";

export const metadata: Metadata = {
  title: "Kaelis Promo",
  description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Wrapper>
      {children}
    </Wrapper>
  );
}
