import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.scss";
import { Background } from "@/components/ui";

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kaelis Promo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistInter.variable}`}>
        <Background/>
        {children}
      </body>
    </html>
  );
}