import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.scss";
import '@/styles/root.scss';
import { Background } from "@/components/ui";
import { ModalProvider } from "@/context/modal";
import { ModalJoin } from "@/components/sections";

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kaelis Promo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistInter.variable}`}>
        <ModalProvider>
          <ModalJoin />
          <Background/>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}