import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.scss";
import '@/styles/root.scss';
import { Background } from "@/components/ui";
import { ModalProvider } from "@/context/modal";
import { Modal } from "@/components/sections";
import NetlifyForm from "@/components/ui/netlify_form";
import {Wrapper} from "@/components/sections";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { setRequestLocale } from "next-intl/server";

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kaelis Promo",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.svg",
  }
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {

  const {locale} = await params;
  console.log('locale',locale)
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  
  return (
    <html lang={locale}>
      <body className={`${geistInter.variable}`}>
        <NextIntlClientProvider>
          <ModalProvider>
            <Modal />
            <Background/>
            <Wrapper>
              {children}
            </Wrapper>
          </ModalProvider>
          <NetlifyForm/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}